FROM mysql:8.4

ADD https://raw.githubusercontent.com/otland/forgottenserver/refs/heads/master/schema.sql /docker-entrypoint-initdb.d/tfs_schema.sql

RUN chown -R mysql:mysql /docker-entrypoint-initdb.d/

EXPOSE 3306
